apiVersion: v1
kind: PersistentVolume
metadata: 
  name: amaccess-dev-volume
  namespace: amaccess-dev 
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  glusterfs:
    endpoints: amaccess-dev-endpoint
    path: etcd
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    namespace: amaccess-dev
    name: etcd
