apiVersion: v1
kind: PersistentVolume
metadata: 
  name: asb-etcd-glusterfs-volume
  namespace: openshift-ansible-service-broker 
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  glusterfs:
    endpoints: asb-etcd-glusterfs-endpoint
    path: etcd
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    namespace: openshift-ansible-service-broker
    name: etcd
