---
apiVersion: v1
kind: Service
metadata:
  name: logging-glusterfs-service
  namespace: logging
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: logging-glusterfs-endpoint
  namespace: logging
subsets:
  - addresses:
    - ip: 10.122.250.62
    ports:
      - port: 1
  - addresses:
    - ip: 10.122.250.63
    ports:
      - port: 1
  - addresses:
    - ip: 10.122.250.64
    ports:
      - port: 1
