apiVersion: v1
kind: PersistentVolume
metadata: 
  name: logging-volume-1
  namespace: logging
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 750Gi
  hostPath:
    path: /esdata1
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    namespace: logging
    name: logging-es-0
