apiVersion: v1
kind: PersistentVolume
metadata: 
  name: registry-volume
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  glusterfs:
    endpoints: glusterfs-endpoint
    path: registry
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    namespace: default
    name: registry-claim
