---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: metrics-cassandra-volume-1
  namespace: openshift-infra
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 75Gi
  hostPath:
    path: /cassandra/data-1
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: metrics-cassandra-1
    namespace: openshift-infra
---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: metrics-cassandra-volume-2
  namespace: openshift-infra
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 75Gi
  hostPath:
    path: /cassandra/data-2
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: metrics-cassandra-2
    namespace: openshift-infra
---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: metrics-cassandra-volume-3
  namespace: openshift-infra
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 75Gi
  hostPath:
    path: /cassandra/data-3
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: metrics-cassandra-3
    namespace: openshift-infra
